### ISSUE TITLE
image

### ISSUE THREAD

**Issue by wulandrima1** [karatuno/Facebook-Group-bot#1]
how to post image + text?

**Comment by karatuno** [comment]
Sorry, this script does not support images. I'll add image support in future
Also, use this script at your own risk, it may lead to a ban of your Facebook account if used in excess. Sorry for the trouble.

**Comment by wulandrima1** [comment]
> Sorry, this script does not support images. I'll add image support in future
> Also, use this script at your own risk, it may lead to a ban of your Facebook account if used in excess. Sorry for the trouble.

thanks..
im waiting 'image support in future'
